FROM node:14.12.0

WORKDIR /app
# Copy package.json package-lock.json tsconfig.json
COPY ./package.json /app/
COPY ./tsconfig.json /app/

# Copy .env file
COPY .env /app/

# Install dev modules
RUN npm install --no-optional

# Copy and compile files
COPY src /app/src
COPY public /app/public

# Entrypoint
CMD [ "npm", "run", "start" ]
