name: Publish Docker image
on:
  push:
    branches:
      - dev
jobs:
  buildx:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Available platforms
      #   run: echo "Available platforms - ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        env:
          IMAGE: ${{ secrets.DOCKER_IMAGE_TAG_NAME_API }}
          PLATFORM: linux/arm/v7,linux/amd64
        run: |
          cd ./api && \
          docker buildx build --push --platform $PLATFORM -t $IMAGE:latest .

      - name: Deploy to cluster
        if: ${{ success() }}
        uses: steebchen/kubectl@v2.0.0
        env:
          DEPLOYMENT: ${{ secrets.DEPLOYMENT_NAME_API }}
          CONTAINER: ${{ secrets.KUBE_CONTAINER_NAME_API }}
          IMAGE: ${{ secrets.DOCKER_IMAGE_TAG_NAME_API }}:latest
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.22.1
          # command: set image $DEPLOYMENT $CONTAINER=$IMAGE
          command: rollout restart $DEPLOYMENT

      - name: Verify deployment
        if: ${{ success() }}
        uses: steebchen/kubectl@v2.0.0
        env:
          DEPLOYMENT: ${{ secrets.DEPLOYMENT_NAME_API }}
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.22.1
          command: rollout status $DEPLOYMENT
